version: '3.8'

services:
 
  db:
    container_name: curso_dev_db
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: user
      POSTGRES_DB: curso_dev
    ports:
      - "5432:5432"

